### ISSUE TITLE
Lab3 замечания

### ISSUE THREAD

**Issue by Andrewbooq** [zaldaria/PP_lab3#1]
Всё правильно, одно незначительное замечание: тип `unsigned __stdcall` нужен только для функции run, passQ и GetCntThreads можно отставить как в лабе2.
И я бы в случае ошибки еще выводил диагностическое сообщение, например здесь:
```
HANDLE thread = (HANDLE)_beginthreadex(...
if(thread ==nullptr)
{
    DWORD err = GetLastError();
    printf("Cannot create thread, GetLastError=%u", err);
}
else
{
    threads.emplace_back(thread);
}
```
Исправление можно мне не присылать, лаба зачтена.
Доделывай сюда же через pthread:
```
#if defined _WIN32 || defined _WIN64
    HANDLE thread = (HANDLE)_beginthreadex...
#elif defined __linux__
#include <errno.h>
...
    pthread_t thread;
    int result = pthread_create(&thread, NULL, run, (void *) this);
    if (result == 0)
    {
        threads.emplace_back(thread);
    }
    else
    {
        printf("Cannot create thread, errno=%d", errno);
    }
#endif
```

**Comment by zaldaria** [comment]
Учла ваше замечание и дописала сообщение об ошибке, оставила __stdcall только для run
 
Доделала условную компиляцию

**Comment by Andrewbooq** [comment]
В целом всё ок, только я не понял, если мы в main делаем вызов `pool.passQ(my_cos, PI * i / 2);` и не проверяем, что возвращается, зачем у нас разные прототипы
```
#if defined (_WIN32) || defined (_WIN64)
void threadsPool::passQ(function<void(double)> f, double p1)
#elif defined __linux__
void* threadsPool::passQ(function<void(double)> f, double p1)  
#endif
```
Почему для линукса void* и возвращается всегда nullptr, который никогда не проверяется и никуда не используется?
Мне кажется можно void  везде и без условной компиляции в объявлении функции. 
Но это так, не существенное замечание для лабы. Если будет время - переделай, если некогда, то оставь как есть.
**Лаба зачтена, жду на зачёте.**

**Comment by zaldaria** [comment]
Поняла, спасибо!
